# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from alvinchow_backend_protobuf import common_pb2 as alvinchow__backend__protobuf_dot_common__pb2
from alvinchow_backend_protobuf import foo_pb2 as alvinchow__backend__protobuf_dot_foo__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AlvinChowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/alvinchow_backend.AlvinChowService/Ping',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=alvinchow__backend__protobuf_dot_common__pb2.SimpleResponse.FromString,
                )
        self.GetFoo = channel.unary_unary(
                '/alvinchow_backend.AlvinChowService/GetFoo',
                request_serializer=alvinchow__backend__protobuf_dot_common__pb2.IdRequest.SerializeToString,
                response_deserializer=alvinchow__backend__protobuf_dot_foo__pb2.Foo.FromString,
                )


class AlvinChowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFoo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlvinChowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=alvinchow__backend__protobuf_dot_common__pb2.SimpleResponse.SerializeToString,
            ),
            'GetFoo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFoo,
                    request_deserializer=alvinchow__backend__protobuf_dot_common__pb2.IdRequest.FromString,
                    response_serializer=alvinchow__backend__protobuf_dot_foo__pb2.Foo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alvinchow_backend.AlvinChowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlvinChowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alvinchow_backend.AlvinChowService/Ping',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            alvinchow__backend__protobuf_dot_common__pb2.SimpleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFoo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alvinchow_backend.AlvinChowService/GetFoo',
            alvinchow__backend__protobuf_dot_common__pb2.IdRequest.SerializeToString,
            alvinchow__backend__protobuf_dot_foo__pb2.Foo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
