version: 0.2

env:
  variables:
    GIT_URL: "git@github.com:alvinchow86/python-backend-template.git"
    DOCKER_REPO: "something.dkr.ecr.us-east-2.amazonaws.com/{% block docker_image%}alvinchow-backend{% endblock %}"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin something.dkr.ecr.us-east-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker pull $DOCKER_REPO:latest || true
  build:
    commands:
      - docker build --cache-from $DOCKER_REPO:latest -t $DOCKER_REPO:latest .
      - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$IMAGE_TAG
  post_build:
    commands:
      - docker push $DOCKER_REPO:$IMAGE_TAG
      - docker push $DOCKER_REPO:latest

      {% block deploy_commands %} {% endblock %}
