execution_role: arn:aws:iam::something:role/prod-ecs-task-execution
task_role: arn:aws:iam::role:role/prod-alvinchow-backend
image: something.dkr.ecr.us-east-2.amazonaws.com/alvinchow-backend:latest
services:
  -
    file: prod-alvinchow-backend-web.json
    family: prod-alvinchow-backend-web
    container_name: alvinchow-backend-web
    command: /home/app/entrypoint/run-web.sh
    cpu: 512
    memory: 512
    ports:
      - 80
  -
    file: prod-alvinchow-backend-grpc.json
    family: prod-alvinchow-backend-grpc
    container_name: alvinchow-backend-grpc
    command: /home/app/entrypoint/run-grpc.sh
    cpu: 512
    memory: 512
    ports:
      - 50051
  -
    file: prod-alvinchow-backend-worker.json
    family: prod-alvinchow-backend-worker
    container_name: alvinchow-backend-worker
    command: /home/app/entrypoint/run-worker.sh
    cpu: 256
    memory: 512
  -
    file: prod-alvinchow-backend-scheduler.json
    family: prod-alvinchow-backend-scheduler
    container_name: alvinchow-backend-scheduler
    command: /home/app/entrypoint/run-scheduler.sh
    cpu: 256
    memory: 256
  -
    file: prod-alvinchow-backend-admin.json
    family: prod-alvinchow-backend-admin
    container_name: alvinchow-backend-admin
    command: /home/app/entrypoint/run-admin.sh
    cpu: 512
    memory: 512
  -
    file: prod-alvinchow-backend-migration.json
    family: prod-alvinchow-backend-migration
    container_name: alvinchow-backend-migration
    command: /home/app/entrypoint/run-migration.sh
    cpu: 256
    memory: 512
